#!/usr/bin/env ruby
# -*- ruby -*-

ToBackup = ['~/Dropbox/']

class Backup
  def initialize options
    @filename = "backup-#{Time.new.strftime("%Y-%m-%d-%H:%M:%S")}.tar"
  end

  def create
    system *(["tar", "cvf", @filename] + ToBackup.map { |file| File.expand_path file })
  end
end

require 'optparse'

options={}
OptionParser.new do |op|
  op.on("--test") { options[:test] = true }
end.parse!

if options[:test]
  require 'minitest/autorun'

  describe "exploratory testing with tar" do

  end
else
  Backup.new(options).create
end

